{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bitcoind.name" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  target:
    name: {{ include "bitcoind.rpcPasswordSecretName" . }}
    creationPolicy: Owner
  data:
    {{- .Values.externalSecrets.data | toYaml | trim | nindent 4 }}
{{- end }}
