{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "bitcoind.name" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  target:
    name: {{ include "bitcoind.name" . }}
    creationPolicy: Owner
  data:
    - secretKey: rpcuser
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.rpcuser.key }}
        {{- if .Values.externalSecrets.remoteRefs.rpcuser.property }}
        property: {{ .Values.externalSecrets.remoteRefs.rpcuser.property }}
        {{- end }}
    - secretKey: rpcpassword
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRefs.rpcpassword.key }}
        {{- if .Values.externalSecrets.remoteRefs.rpcpassword.property }}
        property: {{ .Values.externalSecrets.remoteRefs.rpcpassword.property }}
        {{- end }}
{{- end }}
